// Define the types for ESG metrics
export interface ESGMetric {
  id: string;
  name: string;
  description: string;
  unit: string;
  source: 'GIIN' | 'GRI' | 'Custom';
  framework: string;
  relatedTopic: string;
  category: 'Environmental' | 'Social' | 'Governance';
  dataType: 'Numeric' | 'Percentage' | 'Text' | 'Boolean';
}

export interface ESGMetricWithTracking extends ESGMetric {
  baselineDate?: string;
  baselineValue?: string | number | boolean;
  targetDate?: string;
  targetValue?: string | number | boolean;
  collectionFrequency: 'Daily' | 'Weekly' | 'Monthly' | 'Quarterly' | 'Bi-Annually' | 'Annually' | 'Never';
  dataPoints: {
    date: string;
    value: string | number | boolean;
  }[];
  isSelected: boolean;
}

// GIIN Impact Metrics data
export const giinMetrics: ESGMetric[] = [
  {
    id: 'giin_ghg',
    name: 'Greenhouse Gas Emissions',
    description: 'Total greenhouse gas emissions of the organization',
    unit: 'Metric tons of CO2 equivalent',
    source: 'GIIN',
    framework: 'IRIS+',
    relatedTopic: 'climate',
    category: 'Environmental',
    dataType: 'Numeric'
  },
  {
    id: 'giin_water',
    name: 'Water Consumption',
    description: 'Volume of water consumed by the organization',
    unit: 'Cubic meters',
    source: 'GIIN',
    framework: 'IRIS+',
    relatedTopic: 'water',
    category: 'Environmental',
    dataType: 'Numeric'
  },
  {
    id: 'giin_energy',
    name: 'Energy Consumption',
    description: 'Total energy consumed by the organization',
    unit: 'MWh',
    source: 'GIIN',
    framework: 'IRIS+',
    relatedTopic: 'energy',
    category: 'Environmental',
    dataType: 'Numeric'
  },
  {
    id: 'giin_waste',
    name: 'Waste Generated',
    description: 'Total waste generated by the organization',
    unit: 'Metric tons',
    source: 'GIIN',
    framework: 'IRIS+',
    relatedTopic: 'waste',
    category: 'Environmental',
    dataType: 'Numeric'
  },
  {
    id: 'giin_diversity',
    name: 'Gender Diversity',
    description: 'Percentage of women in leadership positions',
    unit: 'Percentage',
    source: 'GIIN',
    framework: 'IRIS+',
    relatedTopic: 'diversity',
    category: 'Social',
    dataType: 'Percentage'
  },
  {
    id: 'giin_employee',
    name: 'Employee Turnover',
    description: 'Rate of employee departures',
    unit: 'Percentage',
    source: 'GIIN',
    framework: 'IRIS+',
    relatedTopic: 'employeeWellbeing',
    category: 'Social',
    dataType: 'Percentage'
  },
  {
    id: 'giin_training',
    name: 'Employee Training',
    description: 'Average hours of training per employee',
    unit: 'Hours',
    source: 'GIIN',
    framework: 'IRIS+',
    relatedTopic: 'employeeWellbeing',
    category: 'Social',
    dataType: 'Numeric'
  },
  {
    id: 'giin_community',
    name: 'Community Investment',
    description: 'Total investment in community programs',
    unit: 'USD',
    source: 'GIIN',
    framework: 'IRIS+',
    relatedTopic: 'communityEngagement',
    category: 'Social',
    dataType: 'Numeric'
  },
  {
    id: 'giin_board',
    name: 'Board Independence',
    description: 'Percentage of independent board members',
    unit: 'Percentage',
    source: 'GIIN',
    framework: 'IRIS+',
    relatedTopic: 'ethics',
    category: 'Governance',
    dataType: 'Percentage'
  },
  {
    id: 'giin_ethics',
    name: 'Ethics Training',
    description: 'Percentage of employees trained on ethics',
    unit: 'Percentage',
    source: 'GIIN',
    framework: 'IRIS+',
    relatedTopic: 'ethics',
    category: 'Governance',
    dataType: 'Percentage'
  }
];

// GRI Metrics data
export const griMetrics: ESGMetric[] = [
  {
    id: 'gri_305',
    name: 'GRI 305: GHG Emissions',
    description: 'Direct (Scope 1) GHG emissions',
    unit: 'Metric tons of CO2 equivalent',
    source: 'GRI',
    framework: 'GRI Standards',
    relatedTopic: 'climate',
    category: 'Environmental',
    dataType: 'Numeric'
  },
  {
    id: 'gri_302',
    name: 'GRI 302: Energy Consumption',
    description: 'Energy consumption within the organization',
    unit: 'Joules or multiples',
    source: 'GRI',
    framework: 'GRI Standards',
    relatedTopic: 'energy',
    category: 'Environmental',
    dataType: 'Numeric'
  },
  {
    id: 'gri_303',
    name: 'GRI 303: Water and Effluents',
    description: 'Water withdrawal by source',
    unit: 'Megaliters',
    source: 'GRI',
    framework: 'GRI Standards',
    relatedTopic: 'water',
    category: 'Environmental',
    dataType: 'Numeric'
  },
  {
    id: 'gri_306',
    name: 'GRI 306: Waste',
    description: 'Waste by type and disposal method',
    unit: 'Metric tons',
    source: 'GRI',
    framework: 'GRI Standards',
    relatedTopic: 'waste',
    category: 'Environmental',
    dataType: 'Numeric'
  },
  {
    id: 'gri_401',
    name: 'GRI 401: Employment',
    description: 'New employee hires and employee turnover',
    unit: 'Number and rate',
    source: 'GRI',
    framework: 'GRI Standards',
    relatedTopic: 'employeeWellbeing',
    category: 'Social',
    dataType: 'Numeric'
  },
  {
    id: 'gri_403',
    name: 'GRI 403: Occupational Health and Safety',
    description: 'Work-related injuries',
    unit: 'Number and rate',
    source: 'GRI',
    framework: 'GRI Standards',
    relatedTopic: 'employeeWellbeing',
    category: 'Social',
    dataType: 'Numeric'
  },
  {
    id: 'gri_404',
    name: 'GRI 404: Training and Education',
    description: 'Average hours of training per year per employee',
    unit: 'Hours',
    source: 'GRI',
    framework: 'GRI Standards',
    relatedTopic: 'employeeWellbeing',
    category: 'Social',
    dataType: 'Numeric'
  },
  {
    id: 'gri_405',
    name: 'GRI 405: Diversity and Equal Opportunity',
    description: 'Diversity of governance bodies and employees',
    unit: 'Percentage',
    source: 'GRI',
    framework: 'GRI Standards',
    relatedTopic: 'diversity',
    category: 'Social',
    dataType: 'Percentage'
  },
  {
    id: 'gri_413',
    name: 'GRI 413: Local Communities',
    description: 'Operations with local community engagement, impact assessments, and development programs',
    unit: 'Percentage',
    source: 'GRI',
    framework: 'GRI Standards',
    relatedTopic: 'communityEngagement',
    category: 'Social',
    dataType: 'Percentage'
  },
  {
    id: 'gri_205',
    name: 'GRI 205: Anti-corruption',
    description: 'Confirmed incidents of corruption and actions taken',
    unit: 'Number',
    source: 'GRI',
    framework: 'GRI Standards',
    relatedTopic: 'ethics',
    category: 'Governance',
    dataType: 'Numeric'
  },
  {
    id: 'gri_206',
    name: 'GRI 206: Anti-competitive Behavior',
    description: 'Legal actions for anti-competitive behavior, anti-trust, and monopoly practices',
    unit: 'Number',
    source: 'GRI',
    framework: 'GRI Standards',
    relatedTopic: 'ethics',
    category: 'Governance',
    dataType: 'Numeric'
  }
];

// Helper function to get metrics by topic
export const getMetricsByTopic = (topicId: string): ESGMetric[] => {
  const relatedGiinMetrics = giinMetrics.filter(metric => metric.relatedTopic === topicId);
  const relatedGriMetrics = griMetrics.filter(metric => metric.relatedTopic === topicId);
  
  return [...relatedGiinMetrics, ...relatedGriMetrics];
};

// Helper function to get default metrics tracking data
export const getDefaultMetricTracking = (metric: ESGMetric): ESGMetricWithTracking => {
  return {
    ...metric,
    collectionFrequency: 'Monthly',
    dataPoints: [],
    isSelected: false
  };
};
