// IRIS+ Metrics Database for Standard Material Topics
// This contains recommended metrics from the IRIS+ system for various ESG material topics

export interface IRISMetric {
  id: string;
  name: string;
  description: string;
  unit: string;
  category: 'Environmental' | 'Social' | 'Governance';
  framework: 'IRIS+' | 'GRI' | 'SASB' | 'TCFD';
  dataType: 'Numeric' | 'Percentage' | 'Text' | 'Boolean';
  collectionFrequency: 'Monthly' | 'Quarterly' | 'Annually';
  materialTopics: string[];
}

export const irisMetricsDatabase: IRISMetric[] = [
  // Climate Change & GHG Emissions
  {
    id: 'iris-ghg-001',
    name: 'Total GHG Emissions (Scope 1)',
    description: 'Direct greenhouse gas emissions from owned or controlled sources',
    unit: 'tCO2e',
    category: 'Environmental',
    framework: 'IRIS+',
    dataType: 'Numeric',
    collectionFrequency: 'Annually',
    materialTopics: ['climate-change', 'ghg-emissions']
  },
  {
    id: 'iris-ghg-002',
    name: 'Total GHG Emissions (Scope 2)',
    description: 'Indirect greenhouse gas emissions from purchased energy',
    unit: 'tCO2e',
    category: 'Environmental',
    framework: 'IRIS+',
    dataType: 'Numeric',
    collectionFrequency: 'Annually',
    materialTopics: ['climate-change', 'ghg-emissions']
  },
  {
    id: 'iris-ghg-003',
    name: 'Total GHG Emissions (Scope 3)',
    description: 'Indirect greenhouse gas emissions from value chain activities',
    unit: 'tCO2e',
    category: 'Environmental',
    framework: 'IRIS+',
    dataType: 'Numeric',
    collectionFrequency: 'Annually',
    materialTopics: ['climate-change', 'ghg-emissions']
  },
  {
    id: 'iris-energy-001',
    name: 'Total Energy Consumption',
    description: 'Total energy consumed from all sources',
    unit: 'MWh',
    category: 'Environmental',
    framework: 'IRIS+',
    dataType: 'Numeric',
    collectionFrequency: 'Monthly',
    materialTopics: ['energy-management', 'climate-change']
  },
  {
    id: 'iris-energy-002',
    name: 'Renewable Energy Consumption',
    description: 'Energy consumed from renewable sources',
    unit: '%',
    category: 'Environmental',
    framework: 'IRIS+',
    dataType: 'Percentage',
    collectionFrequency: 'Monthly',
    materialTopics: ['energy-management', 'renewable-energy']
  },

  // Water Management
  {
    id: 'iris-water-001',
    name: 'Total Water Consumption',
    description: 'Total volume of water consumed by the organization',
    unit: 'm³',
    category: 'Environmental',
    framework: 'IRIS+',
    dataType: 'Numeric',
    collectionFrequency: 'Monthly',
    materialTopics: ['water-management', 'water-stewardship']
  },
  {
    id: 'iris-water-002',
    name: 'Water Recycling Rate',
    description: 'Percentage of water recycled and reused',
    unit: '%',
    category: 'Environmental',
    framework: 'IRIS+',
    dataType: 'Percentage',
    collectionFrequency: 'Quarterly',
    materialTopics: ['water-management', 'circular-economy']
  },

  // Waste Management
  {
    id: 'iris-waste-001',
    name: 'Total Waste Generated',
    description: 'Total amount of waste generated by operations',
    unit: 'tonnes',
    category: 'Environmental',
    framework: 'IRIS+',
    dataType: 'Numeric',
    collectionFrequency: 'Monthly',
    materialTopics: ['waste-management', 'circular-economy']
  },
  {
    id: 'iris-waste-002',
    name: 'Waste Diversion Rate',
    description: 'Percentage of waste diverted from landfill',
    unit: '%',
    category: 'Environmental',
    framework: 'IRIS+',
    dataType: 'Percentage',
    collectionFrequency: 'Monthly',
    materialTopics: ['waste-management', 'circular-economy']
  },
  {
    id: 'iris-waste-003',
    name: 'Hazardous Waste Generated',
    description: 'Total amount of hazardous waste generated',
    unit: 'tonnes',
    category: 'Environmental',
    framework: 'IRIS+',
    dataType: 'Numeric',
    collectionFrequency: 'Quarterly',
    materialTopics: ['waste-management', 'pollution-prevention']
  },

  // Biodiversity & Ecosystems
  {
    id: 'iris-bio-001',
    name: 'Land Under Sustainable Management',
    description: 'Area of land under sustainable management practices',
    unit: 'hectares',
    category: 'Environmental',
    framework: 'IRIS+',
    dataType: 'Numeric',
    collectionFrequency: 'Annually',
    materialTopics: ['biodiversity', 'land-use', 'ecosystem-services']
  },

  // Employee Relations & Development
  {
    id: 'iris-emp-001',
    name: 'Employee Turnover Rate',
    description: 'Percentage of employees who left the organization',
    unit: '%',
    category: 'Social',
    framework: 'IRIS+',
    dataType: 'Percentage',
    collectionFrequency: 'Quarterly',
    materialTopics: ['employee-relations', 'talent-management', 'human-capital']
  },
  {
    id: 'iris-emp-002',
    name: 'Training Hours per Employee',
    description: 'Average training hours provided per employee',
    unit: 'hours',
    category: 'Social',
    framework: 'IRIS+',
    dataType: 'Numeric',
    collectionFrequency: 'Quarterly',
    materialTopics: ['employee-development', 'human-capital', 'training']
  },
  {
    id: 'iris-emp-003',
    name: 'Employee Satisfaction Score',
    description: 'Average employee satisfaction score from surveys',
    unit: 'score (1-10)',
    category: 'Social',
    framework: 'IRIS+',
    dataType: 'Numeric',
    collectionFrequency: 'Annually',
    materialTopics: ['employee-relations', 'workplace-culture']
  },

  // Diversity & Inclusion
  {
    id: 'iris-div-001',
    name: 'Gender Diversity in Leadership',
    description: 'Percentage of women in leadership positions',
    unit: '%',
    category: 'Social',
    framework: 'IRIS+',
    dataType: 'Percentage',
    collectionFrequency: 'Annually',
    materialTopics: ['diversity-inclusion', 'gender-equality', 'leadership']
  },
  {
    id: 'iris-div-002',
    name: 'Ethnic Diversity in Workforce',
    description: 'Percentage of ethnic minorities in total workforce',
    unit: '%',
    category: 'Social',
    framework: 'IRIS+',
    dataType: 'Percentage',
    collectionFrequency: 'Annually',
    materialTopics: ['diversity-inclusion', 'equal-opportunity']
  },

  // Health & Safety
  {
    id: 'iris-safety-001',
    name: 'Total Recordable Incident Rate (TRIR)',
    description: 'Number of recordable incidents per 200,000 work hours',
    unit: 'incidents per 200k hours',
    category: 'Social',
    framework: 'IRIS+',
    dataType: 'Numeric',
    collectionFrequency: 'Monthly',
    materialTopics: ['occupational-health-safety', 'workplace-safety']
  },
  {
    id: 'iris-safety-002',
    name: 'Lost Time Injury Frequency Rate',
    description: 'Number of lost time injuries per million work hours',
    unit: 'injuries per million hours',
    category: 'Social',
    framework: 'IRIS+',
    dataType: 'Numeric',
    collectionFrequency: 'Monthly',
    materialTopics: ['occupational-health-safety', 'workplace-safety']
  },

  // Community Impact
  {
    id: 'iris-community-001',
    name: 'Community Investment',
    description: 'Total monetary investment in community programs',
    unit: '$',
    category: 'Social',
    framework: 'IRIS+',
    dataType: 'Numeric',
    collectionFrequency: 'Quarterly',
    materialTopics: ['community-relations', 'social-impact']
  },
  {
    id: 'iris-community-002',
    name: 'Local Employment Rate',
    description: 'Percentage of employees hired from local communities',
    unit: '%',
    category: 'Social',
    framework: 'IRIS+',
    dataType: 'Percentage',
    collectionFrequency: 'Annually',
    materialTopics: ['community-relations', 'local-employment']
  },

  // Governance & Ethics
  {
    id: 'iris-gov-001',
    name: 'Board Independence',
    description: 'Percentage of independent directors on the board',
    unit: '%',
    category: 'Governance',
    framework: 'IRIS+',
    dataType: 'Percentage',
    collectionFrequency: 'Annually',
    materialTopics: ['corporate-governance', 'board-effectiveness']
  },
  {
    id: 'iris-gov-002',
    name: 'Ethics Training Completion Rate',
    description: 'Percentage of employees who completed ethics training',
    unit: '%',
    category: 'Governance',
    framework: 'IRIS+',
    dataType: 'Percentage',
    collectionFrequency: 'Annually',
    materialTopics: ['business-ethics', 'compliance', 'training']
  },
  {
    id: 'iris-gov-003',
    name: 'Data Privacy Incidents',
    description: 'Number of data privacy incidents or breaches',
    unit: 'count',
    category: 'Governance',
    framework: 'IRIS+',
    dataType: 'Numeric',
    collectionFrequency: 'Quarterly',
    materialTopics: ['data-privacy', 'cybersecurity', 'risk-management']
  },

  // Supply Chain & Human Rights
  {
    id: 'iris-supply-001',
    name: 'Supplier Code of Conduct Compliance',
    description: 'Percentage of suppliers with signed code of conduct',
    unit: '%',
    category: 'Social',
    framework: 'IRIS+',
    dataType: 'Percentage',
    collectionFrequency: 'Annually',
    materialTopics: ['supply-chain-management', 'human-rights']
  },
  {
    id: 'iris-supply-002',
    name: 'Supplier Sustainability Assessments',
    description: 'Percentage of suppliers assessed for sustainability',
    unit: '%',
    category: 'Social',
    framework: 'IRIS+',
    dataType: 'Percentage',
    collectionFrequency: 'Annually',
    materialTopics: ['supply-chain-management', 'sustainable-sourcing']
  }
];

// Helper function to get IRIS+ metrics for a specific material topic
export const getIRISMetricsByTopic = (topicId: string): IRISMetric[] => {
  return irisMetricsDatabase.filter(metric => 
    metric.materialTopics.some(topic => 
      topic.toLowerCase().includes(topicId.toLowerCase()) ||
      topicId.toLowerCase().includes(topic.toLowerCase())
    )
  );
};

// Helper function to check if a topic is a standard material topic (has IRIS+ metrics)
export const isStandardMaterialTopic = (topicId: string): boolean => {
  return getIRISMetricsByTopic(topicId).length > 0;
};