// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpdazlcswyottzpwcmes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwZGF6bGNzd3lvdHR6cHdjbWVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4ODYxMDIsImV4cCI6MjA3MDQ2MjEwMn0.subTnAfP-tkmd2BkVt2Q5I1BCy6jtuHMgJNtiL3HlEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});