
import { ESGMetric } from './types';

// GIIN Impact Metrics data
export const giinMetrics: ESGMetric[] = [
  {
    id: 'giin_ghg',
    name: 'Greenhouse Gas Emissions',
    description: 'Total greenhouse gas emissions of the organization',
    unit: 'Metric tons of CO2 equivalent',
    source: 'GIIN',
    framework: 'IRIS+',
    relatedTopic: 'climate',
    category: 'Environmental',
    dataType: 'Numeric'
  },
  {
    id: 'giin_water',
    name: 'Water Consumption',
    description: 'Volume of water consumed by the organization',
    unit: 'Cubic meters',
    source: 'GIIN',
    framework: 'IRIS+',
    relatedTopic: 'water',
    category: 'Environmental',
    dataType: 'Numeric'
  },
  {
    id: 'giin_energy',
    name: 'Energy Consumption',
    description: 'Total energy consumed by the organization',
    unit: 'MWh',
    source: 'GIIN',
    framework: 'IRIS+',
    relatedTopic: 'energy',
    category: 'Environmental',
    dataType: 'Numeric'
  },
  {
    id: 'giin_waste',
    name: 'Waste Generated',
    description: 'Total waste generated by the organization',
    unit: 'Metric tons',
    source: 'GIIN',
    framework: 'IRIS+',
    relatedTopic: 'waste',
    category: 'Environmental',
    dataType: 'Numeric'
  },
  {
    id: 'giin_diversity',
    name: 'Gender Diversity',
    description: 'Percentage of women in leadership positions',
    unit: 'Percentage',
    source: 'GIIN',
    framework: 'IRIS+',
    relatedTopic: 'diversity',
    category: 'Social',
    dataType: 'Percentage'
  },
  {
    id: 'giin_employee',
    name: 'Employee Turnover',
    description: 'Rate of employee departures',
    unit: 'Percentage',
    source: 'GIIN',
    framework: 'IRIS+',
    relatedTopic: 'employeeWellbeing',
    category: 'Social',
    dataType: 'Percentage'
  },
  {
    id: 'giin_training',
    name: 'Employee Training',
    description: 'Average hours of training per employee',
    unit: 'Hours',
    source: 'GIIN',
    framework: 'IRIS+',
    relatedTopic: 'employeeWellbeing',
    category: 'Social',
    dataType: 'Numeric'
  },
  {
    id: 'giin_community',
    name: 'Community Investment',
    description: 'Total investment in community programs',
    unit: 'USD',
    source: 'GIIN',
    framework: 'IRIS+',
    relatedTopic: 'communityEngagement',
    category: 'Social',
    dataType: 'Numeric'
  },
  {
    id: 'giin_board',
    name: 'Board Independence',
    description: 'Percentage of independent board members',
    unit: 'Percentage',
    source: 'GIIN',
    framework: 'IRIS+',
    relatedTopic: 'ethics',
    category: 'Governance',
    dataType: 'Percentage'
  },
  {
    id: 'giin_ethics',
    name: 'Ethics Training',
    description: 'Percentage of employees trained on ethics',
    unit: 'Percentage',
    source: 'GIIN',
    framework: 'IRIS+',
    relatedTopic: 'ethics',
    category: 'Governance',
    dataType: 'Percentage'
  }
];
